### ISSUE TITLE
Some info

### ISSUE THREAD

**Issue by emcifuntik** [rfuzzo/CP77Tools#1]
somebool doesn't look like bool, I think it's kind of flag
And you also need to use Zsize for unpacking. I think in your case Zsize = DiskSize and Size = RamSize (unpacked), becase as I see, most of game files have KARK header, I think it's some kind of compression, maybe LZMA based. If you want to cooperate contact me on discord Tuxick#0282

**Comment by emcifuntik** [comment]
And as I can see, your unk1 in FileInfoEntry points to item in table3, and unk2 is last item in table3. Indexes fits to table3 size
![image](https://user-images.githubusercontent.com/4309694/101470411-055f4600-3957-11eb-9cd7-7ce6397e5dd0.png)

On this screenshot it's Unknown3 and Unknown4

**Comment by emcifuntik** [comment]
And first 8 bytes in FileInfoEntry is 100% hash because files sorted by this field to iterate faster

**Comment by rfuzzo** [comment]
thank you! now that I fixed oodle decompression, I can work again on the bytes!
