### ISSUE TITLE
csv generate ?

### ISSUE THREAD

**Issue by barnett2010** [rfuzzo/CP77Tools#13]
How to generate this file？ archivehashes.csv

https://github.com/WolvenKit/CP77Tools/blob/main/CP77Tools/Resources/archivehashes.csv

I want to get a list of this file  “lang_zh-cn_voice.archive“

**Comment by rfuzzo** [comment]
hi! you can type in `archive -l -p "PATH TO lang_zh-cn_voice.archive"`

**Comment by barnett2010** [comment]
Thank you for your reply
I do this
_C:\game\2077jiebao\release (2)>CP77Tools archive -l -p "C:\game\Cyberpunk 2077 104\archive\pc\content\lang_zh-cn_voice.archive"_

Only hash value found?
No file name appears.

_18440268301416375303
18440663469609941030
18440707310809682138
18440872320652421256
18440991545322344017
18441189217778961208
18441508455787520868
18441922619696777713
18442059793694618339
18442216822854852361_


I'll upload this file.
Game version 1.04

http://106.14.223.230:5213/s/4dfdec9c-8177-4f75-b3fa-00b59010a523

**Comment by rfuzzo** [comment]
hmm, I don't have this voice archive... do you download the localisation seperatly?

**Comment by barnett2010** [comment]
cn voice download https://mega.nz/folder/XNoBmaJR#IH9K5J2GBxrJSqIoux7rhw

**Comment by barnett2010** [comment]
lang_zh-cn_voice.archive
：4894334976 byte

MD5     ：FDE3191BB050C4ADB8B4091DD27AC26C
SHA1    ：25E9A5360853181A25529E3604223B3956EDE4DE
CRC32   ：8D8F63D5

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/64mYhNeg/14-github)

**Comment by barnett2010** [comment]
@sodanakin   can not open

**Comment by Offline-R503B** [comment]
@barnett2010 Ah sorry thats just me logging the issue in our Trello.

**Comment by rfuzzo** [comment]
this is fixed here: https://github.com/WolvenKit/CP77Tools/releases/tag/v.0.1.4.0h2

**Comment by barnett2010** [comment]
thank you so much

**Comment by barnett2010** [comment]
> [Important][2020/12/31 16:50:50] Loading local filename hashes...
[Success][2020/12/31 16:50:53] Loaded 1439855 hashes in 3122ms.
base\localization\zh-cn\vo\civ_low_f_04_enus_30_sts_std_arr_01_f_1811ab0bc751300c.wem
base\localization\zh-cn\vo\v_sts_wat_kab_02_m_16ec05ec23559000.wem
base\localization\zh-cn\vo\v_sq023_m_19282a3314386000.wem
base\localization\zh-cn\vo\gang_val_m_15_mex_30_sts_hey_gle_04_f_1ab935ee0b29f000.wem
base\localization\zh-cn\vo\gang_mls_m_08_enus_30_maelstrom_f_1ef9193f9a522004.wem
