### ISSUE TITLE
Extract soundfiles

### ISSUE THREAD

**Issue by zihanw4** [rfuzzo/CP77Tools#14]
I'm trying to extract the dialogue sound files from the localized archive...But when I finished the extraction, what should I do for next step?

thanks,

**Comment by WinkelCode** [comment]
Here is how to do it:

You need this: https://github.com/hcs64/ww2ogg and `Revorb` from the readme of the repo (the IPFS link works and seems to match the checksum of `http://yirkha.fud.cz/progs/foobar2000/revorb.exe`).

Recommended! Install `ffmpeg` to use `ffplay` for ultra convenient playback.

The actual commands to get to the audio files are:

`.\ww2ogg.exe "<Path to audio file>.wem" --pcb packed_codebooks_aoTuV_603.bin` (the last part is important to not get gibberish audio files, turn down the volume just in case! 😄 )

Then you should be able to just use `ffplay.exe <Path to audio file>.ogg`

Reportedly some of these files may have issues with skipping, etc. if you have such issues you should be able to clean them up by simply running `revorb.exe <Path to audio file>.ogg`.

Edit: FYI VLC seems to have difficulty playing files that were not `revorb`'d

**Comment by shinodem** [comment]
How can i get .wem files? Extracted files from lang_en_voice.archive only .bin and .buffer.
Renaming .bin to .wem and using ww2ogg gives
Parse error: missing RIFF
