### ISSUE TITLE
Link to Builds and Build Instructions

### ISSUE THREAD

**Issue by WinkelCode** [rfuzzo/CP77Tools#15]
I think it would be a good idea to 1.) Either link to the Nexusmods page or simply upload builds here as well and 2.) Include build instructions.

I actually didn't see that a build was available on Nexusmods so I ended up building it myself using the .NET 5.0 SDK, `dotnet build --configuration Release` inside the folder with the .sln seems to work just fine.

Edit: Never mind, builds are found under Actions: https://github.com/WolvenKit/CP77Tools/actions Would still be a good idea to have a prominent link to it, it's not exactly apparent where they are.

**Comment by rfuzzo** [comment]
hi! actually, links are found under https://github.com/WolvenKit/CP77Tools/releases

But thank you, I'll add it more prominently in the readme!
