### ISSUE TITLE
future  tools

### ISSUE THREAD

**Issue by Uncle3131** [rfuzzo/CP77Tools#20]
Hello everyone, I'm familiar with modding witcher 3 and he's a terrible, very bad modding. 
Hope you make powerful tools in a year's time so we can compete with the mods of their gta and fallout. 
How's the work going now? How many people work every day? What are you doing at the moment, what do you plan to do next year? 

I don't remember telling the developers that they'd release official tools if they weren't, what are you going to do? Will we get the same limited tools as in witcher 3?

I love adding something of my own to the game and I have a couple of questions, maybe you yes

When presumably we will be able to add our items, weapons, objects, whole cards from other games or made with our own hands. Clothing, tattoo, npc. 

Whether you're going to make your own multiplayer, maybe there are people on your team who will be doing it in a year or two. 

I really like to upgrade the weapon, I've played a lot of one game escape from tarkov, do you think, whether I can in the future, make such a great mod, we can replace a lot of parts with weapons. 
Also, the customization of the character, whether we can add more and more areas of bodies, for example, to customize the legs, hands, etc.

So, what about adding your animations? Are you working happy about it? Is there progress? 

And, for example, can we make transport better when you shoot into the water so that there are splashes of water, a more realistic car system, damage to the car, and so on. 

I'm very interested in watching this, I hope you make some cool tools. 

Good luck.

**Comment by Moonded** [comment]
Hey!

We are going to make better modding support then W3 got. We are working day and night on it and like that you are interested in watching. We are making good progress, but I can't say for now what we will be able to mod in the future!
A multiplayer won't be released by us and will never be in production by the community, because a full fletched multiplayer is planed by CDPR themselves.

If you have any questions regarding what we are actually working on, consider [joining our discord](https://discord.gg/Epkq79kd96).

Until then cheers,
Moonded

---
Community Management
Discord: Moonded#0001

**Comment by Uncle3131** [comment]
> Hey!
> 
> We are going to make better modding support then W3 got. We are working day and night on it and like that you are interested in watching. We are making good progress, but I can't say for now what we will be able to mod in the future!
> A multiplayer won't be released by us and will never be in production by the community, because a full fletched multiplayer is planed by CDPR themselves.
> 
> If you have any questions regarding what we are actually working on, consider [joining our discord](https://discord.gg/Epkq79kd96).
> 
> Until then cheers,
> Moonded
> 
> ---
> Community Management
> Discord: Moonded#0001

I don't always have time to follow him, I missed a lot, I'd like you to answer the questions I asked, I really hope I can do it in time, thank you.

**Comment by rfuzzo** [comment]
tw3 actually is quite decent to mod.

as for the rest: stuff will be done, when it's done.

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/64mYhNeg/14-github)
