### ISSUE TITLE
"lang_en_text.archive" The localization file "cr2w" to text Strings (CAN YOU DO IT!!!)

### ISSUE THREAD

**Issue by 4Brad-23** [rfuzzo/CP77Tools#25]
All the dialogue/conversations in the "lang_en_text.archive"...!

**Comment by avail** [comment]
The cr2w tool does not export the files themselves just yet, it just exports metadata contained in them

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/64mYhNeg/14-github)

**Comment by 4Brad-23** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Github](https://trello.com/c/64mYhNeg/14-github)

The link is asking for an invite - Appreciated the help but what's this for...!
