### ISSUE TITLE
About Oodle compression

### ISSUE THREAD

**Issue by eprilx** [rfuzzo/CP77Tools#3]
For oodle version 6 or higher, the paramters of compress function should be
`OodleLZ_Compress(OodleFormat format, byte[] buffer, long bufferSize, byte[] outputBuffer, OodleCompressionLevel level, uint unused1, uint unused2, uint unused3, uint unused4, uint unused5)`
Btw, this game use format 8 (Kraken) and level 9 (maximum).

**Comment by rfuzzo** [comment]
thank you!
