### ISSUE TITLE
How can I extract a specific folder instead of the full Archive?

### ISSUE THREAD

**Issue by 4Brad-23** [rfuzzo/CP77Tools#40]

**Comment by phrisk** [comment]
You can use either the pattern or regex option for this

    -w, --pattern <pattern>              Use optional search pattern, e.g. *.ink. If bith regex and pattern is definedm, pattern will be used first
    -r, --regex <regex>                  Use optional regex pattern.

For example, to extract only **base\localization\en-us\subtitles\open_world\fixers** from **lang_en_text.archive**:

    archive -e -p "C:\Program Files\Steam\steamapps\common\Cyberpunk 2077\archive\pc\content\lang_en_text.archive" -w "base\localization\en-us\subtitles\open_world\fixers\*"

**Comment by phrisk** [comment]
NB: In the future support queries would be better asked in the [CP77Tools Support Channel](https://discord.gg/cp77modding), you'll likely get a quicker response too 👍

**Comment by 4Brad-23** [comment]
> 
> 
> NB: In the future support queries would be better asked in the [CP77Tools Support Channel](https://discord.gg/cp77modding), you'll likely get a quicker response too 👍

Yeah, I know I was just checking if the author is still with us!
