### ISSUE TITLE
about dds

### ISSUE THREAD

**Issue by barnett2010** [rfuzzo/CP77Tools#43]
thank you 

The picture needs to be flipped vertically
This function should be added to the script  

:)

**Comment by rfuzzo** [comment]
Yes that’s a good idea. However, the tools do extract the textures exactly as they are inside the archive. 
QoL features will be added later.

**Comment by AtilioA** [comment]
should this be closed?

**Comment by rfuzzo** [comment]
Can be closed, I’ll add a note to importing - we need to be aware that textures might need to be flipped before packing
