### ISSUE TITLE
Could not convert most textures

### ISSUE THREAD

**Issue by daniel-halodi** [rfuzzo/CP77Tools#44]
Using ` archive -u --uext png -p "FILEPATH.arcive"` results in only a few textures being converted, while most of them return a red error message `[Error] Could not convert`.

Any ideas on what causes this? Is something wrong with the conversion tool?

**Comment by rfuzzo** [comment]
What archive are you extracting?

**Comment by drd-droid1** [comment]
I had a similar issue as well. Trying to extract using TGA, gives me red messages too. The archive I extracted from was I believe the "basegame_4_gamedata". Is this the correct place where textures from NPCs, clothing, etc. are at?

**Comment by rfuzzo** [comment]
For Base game 4, the tools convert all but one texture without errors.

**Comment by daniel-halodi** [comment]
My appologies for the late reply. I tried to extract "basegame_3_nightcity"
