### ISSUE TITLE
about json 。Dialogue text

### ISSUE THREAD

**Issue by barnett2010** [rfuzzo/CP77Tools#48]
Unpack this file。lang_en_text.archive
Get a lot of JSON files
Open these json files
The dialog is displayed normally.
Code not displayed
![2020-12-31_174651](https://user-images.githubusercontent.com/8305408/103405035-a75a0300-4b90-11eb-894d-664cfdcabab3.jpg)

How to decrypt it

**Comment by rfuzzo** [comment]
these are not real json files. I know it's confusing.

CDPR just called their own JsonResource file format .json.

**Comment by barnett2010** [comment]
Oh, I see。

thank you so much

**Comment by DanRuta** [comment]
@barnett2010 @rfuzzo 

Is there/have you found a way to get the "clean" data from these files? I'm suspecting it's just a matter of getting the right encoding/decoding, but the closest I got was the contents in that screenshot through python.

I'm hoping/assuming there is more data in there mapping the dialogue lines to the audio files (via their ID or something similar).
