### ISSUE TITLE
text.archive related issues

### ISSUE THREAD

**Issue by Minidoracat** [rfuzzo/CP77Tools#7]
text.archive Unpacking out of the JSON format is wrong, is this a game engine problem?

https://cdn.discordapp.com/attachments/456737824725794827/787037632890011648/unknown.png

**Comment by Morgawr** [comment]
I'm not familiar with these formats but I just played around with it myself as well and it seems like these json files are actually compressed/archived somewhat.

If you run something like "./CP77Tools.exe cr2w -a -p <path_to_file.json>" it will (sometimes at least, sometimes it crashes) dump some extra json metadata. I'm not entirely sure how this works though, I'm trying to extract the localization files in readable text format but I can't get to the actual data. 

Hopefully @rfuzzo is able to chime in with more knowledge on this.

**Comment by rfuzzo** [comment]
these are not actually .json files, CDPR just re-used that extension. in Reality they are CR2W redengine files, which will be able to be read with the CP77 modding tools in the (near) future!
