### ISSUE TITLE
Data lost during uncook or rebuild/pack

### ISSUE THREAD

**Issue by Akiway** [rfuzzo/CP77Tools#72]
### Process to the issue
1. Uncook a random cloth from \basegame_4_gamedata
2. Get a mesh file of 592 KB, a 0.buffer of 33KB and a 1.buffer of 2419 KB
3. Rebuild and pack these (archive size = 572 KB)

From here the archive is working properly.

But now:

4. Take the generated archive and uncook it again
5. Get a mesh file of 592 KB, a 0.buffer of **3 KB** and a 1.buffer of **556 KB**
6. Rebuild and pack these (archive size = **556 KB**)

The archive is not working (game craches).

Both buffers a lot of data, making them not reusable:
![2021-01-26 04_20_12-h1_064_specs__sunglasses](https://user-images.githubusercontent.com/23312133/105796653-9766f080-5f8f-11eb-86f3-1a0562995e2e.png)

Command used to rebuild: `rebuild -p <path_to_folder> -t -b --keep --unsaferaw`
Version of CP77Tools used: v.1.1.0.2

**Comment by rfuzzo** [comment]
thank you for your report!
I found the bug and this will be fixed in the next update.

**Comment by rfuzzo** [comment]
this is fixed in https://github.com/WolvenKit/CP77Tools/releases/tag/v.1.1.0.3
