### ISSUE TITLE
Consider move to monorepo

### ISSUE THREAD

**Issue by waitxd** [rfuzzo/CP77Tools#73]
Recently big portion of source code was moved to WolvenKit/Wolven-kit project. Those code is consumed via nuget packages.
However, API-layout is in early stage and not finished yet. 
I'd like to push some perfomance-related PR's that require change of API: for example, use streams for file extraction instead of byte arrays (do not load whole uncompressed 750mb file in memory) or add new compression types instead of Kraken only.
That's require PRs in different repository with different timeline (one have to publish nuget first to consume it here).
And it seems that nuget-packages are not even built from master branch.

I see following options:
- Move completely to WolvenKit/Wolven-kit as their main cli (probably with name change to something like WolvenKit.CLI)
- Move back WolvenKit.Cyberformats at least until API stabilizes.
- I am missing something :)

**Comment by Traderain** [comment]
> And it seems that nuget-packages are not even built from master branch.  

I would like to soon update the CI that it build and creates new nuget packages automatically, I just haven't had time for it yet.
And yeah it can be a bit confusing currently the setup.

**Comment by phrisk** [comment]
Is a monorepo the eventual goal or will CP77Tools forever remain separate from from Wolven-kit?

If the latter, would it make more sense to have these shared `WolvenKit.Common` and `WolvenKit.CyberFormats` dependencies exist in their own repo and have Wolven-kit consume the nuget packages just like CP77Tools?

**Comment by Traderain** [comment]
I think eventually (actually now already) will have all the functionality of the repo so logically this should be archived but if for some reason idk for automation or testing we want a separate repo for the cli tool we can keep this but we can just have that in the main repo. This should be decided by @rfuzzo probably in the end.

**Comment by rfuzzo** [comment]
well here's my thoughts - I didn't move to the monorepo for these reasons:
1. The CLI builds fast and is easy to use in Debug
2. Ideally I would like to have the CLI cross-platform compatible (you can't build the WolvenKit sln outside windows)
3. I always wanted to make a small "REDZip" project which can open and extract .archive files just like 7zip

On the other hand, yes it is slightly more bothersome to maintain two repos, and having all centralized is easier to test...

I'm undecided yet...

**Comment by Traderain** [comment]
1: we can make a second sln file in the repo.
2: yeah thats an issue, we should probably talk about that more
3: not a bad idea

**Comment by waitxd** [comment]
@rfuzzo 
Let me clarify: I'm talking more about merging source control rather than merging with Wolven-Kit GUI under windows-only umbrella. PRs spanning multiple repos is no-go for me if we are talking about spare time projects.
For example, [dotnet/runtime](https://github.com/dotnet/runtime) has over 200 solution projects with different targets and yet centralized in one place. You can see their points about consolidating repos [here](https://github.com/dotnet/runtime/issues/13257).
I see no difficulties about build speeds or DX while debugging when using correct monorepo structure.
Wolven-Kit GUI can still target `net5.0-windows` (until migration to Avalonia or MAUI) and CLI can target `net5.0` and be cross-platform as well.
Users outside Windows ecosystem will be able to develop mods: decompress original kraken-compressed assets with [ooz](https://github.com/powzix/ooz) (or one of forks) and compress modified with LZ4, Zlib or even serve them uncompressed (lz4 is better thought).

**Comment by rfuzzo** [comment]
Ah I see the misunderstanding! Yes, that sounds great actually. Let's go with a mono repo-multi sln structure then. 👍

**Comment by rfuzzo** [comment]
in fact, we can do that right now, as all changes have been merged into the Wolvenkit repo - and the cp77tools repo is remote git-tracked in wolvenkit anyways.

**Comment by rfuzzo** [comment]
Done. I will archive this repo and move the issue to Wolvenkit. Thank you.
